#!/bin/bash
# generate-characterization.sh
# Creates a characterization test file scaffold with proper headers

set -e

USAGE="Usage: $0 <target_file> [output_dir]
Creates a characterization test file scaffold colocated with the target source.

Examples:
  $0 src/utils/parser.py
  $0 src/utils/parser.py tests/
"

TARGET_FILE="$1"
OUTPUT_DIR="${2:-}"

if [ -z "$TARGET_FILE" ]; then
    echo "$USAGE"
    exit 1
fi

if [ ! -f "$TARGET_FILE" ]; then
    echo "Error: target file '$TARGET_FILE' not found"
    exit 1
fi

TARGET_DIR=$(dirname "$TARGET_FILE")
TARGET_BASENAME=$(basename "$TARGET_FILE")
TARGET_NAME="${TARGET_BASENAME%.*}"
TARGET_EXT="${TARGET_BASENAME##*.}"

# Detect test directory
if [ -n "$OUTPUT_DIR" ]; then
    TEST_DIR="$OUTPUT_DIR"
else
    # Look for test directories
    for candidate in "tests" "test" "specs" "spec"; do
        if [ -d "$candidate" ]; then
            TEST_DIR="$candidate"
            break
        fi
    done
    TEST_DIR="${TEST_DIR:-tests}"
    mkdir -p "$TEST_DIR"
fi

# Detect framework from project
if [ -f "pyproject.toml" ] || [ -f "pytest.ini" ]; then
    FRAMEWORK="pytest"
    TEST_EXT=".py"
    TEST_CLASS_PREFIX=""
elif [ -f "jest.config.*" ] || [ -f "vitest.config.*" ]; then
    FRAMEWORK="jest"
    TEST_EXT=".test.ts"
    TEST_CLASS_PREFIX=""
elif [ -f "package.json" ]; then
    FRAMEWORK="jest"
    TEST_EXT=".test.ts"
    TEST_CLASS_PREFIX=""
else
    FRAMEWORK="generic"
    TEST_EXT=".txt"
    TEST_CLASS_PREFIX=""
fi

# Build test file path
RELATIVE_PATH="${TARGET_DIR#$(dirname "$TARGET_FILE" | sed 's|/[^/]*$||')}"
TEST_FILENAME="${TARGET_NAME}.characterization${TEST_EXT}"
TEST_FILEPATH="${TEST_DIR}/${RELATIVE_PATH}/${TEST_FILENAME}"

mkdir -p "$(dirname "$TEST_FILEPATH")"

# Generate scaffold
cat > "$TEST_FILEPATH" << EOF
# Characterization tests for ${TARGET_BASENAME}
# Generated by characterization-testing skill
# IMPORTANT: These tests capture CURRENT behavior, not intended behavior.
# Label any buggy behavior with: // CHARACTERIZATION: ...

import unittest  # or appropriate framework import

# TODO: Replace with actual tests based on observed behavior
class Test${TARGET_NAME}Characterization(unittest.TestCase):
    # CHARACTERIZATION: document current behavior below

    def test_placeholder(self):
        \"\"\"TODO: Replace with actual characterization test\"\"\"
        pass
EOF

echo "Created: $TEST_FILEPATH"
echo "Framework detected: $FRAMEWORK"
echo "Next: Explore the target file and replace placeholder tests with actual behavior tests"